### PR TITLE
fix weird color issue (#14)

### LINKED ISSUE #14: generated color scheme gives some weird colors
Hi again,

I've really been liking `flavours` so far, the main gripe I have is that depending on the image the color scheme generation algorithm can give (imo) some weird color choices. Here is an example:  https://imgur.com/a/U8Aa0kR as you can see the image is quite dark and basically just shades of blue, while the generated colors are very bright neon colors with not much blue, and the background color is a relatively bright purple. 

I can give more examples if needed. I suspect it has trouble finding colors when an image is made up of similar shades of a color ?

I understand that colors are very much subject to personal preference, so if you disagree and deem this to be expected behaviour then please feel free to close this issue.

### PR DESCRIPTION
**Pull request by loiccoyle**
Hi again,

This should fix #14 , it seems it is an issue with the alpha channel, so I basically convert the image to rgba format regardless of it has one and provide the `ColorFormat::Rgba` format.
Keep in mind I basically have no rust experience so if I mishandled anything please let me know.

Before: https://imgur.com/a/U8Aa0kR

After: https://imgur.com/3q2A2lw

As far as I can tell this doesn't break anything, but please try it out.

### CODE REVIEW

**Comment by Misterio77** [comment]
Thanks for the fix!

**Comment by Misterio77** [comment]
I'll be sure to test this with my images to make sure nothing major changes.

I should refactor the code asap to include automatic tests for future pulls, though. I'm a lot better at Rust than i used to be when i wrote flavours, so there's a lot of improvements to be done.

Thanks again for catching and fixing this!

**Comment by Misterio77** [comment]
It seems the changes are pretty minor. The trim colors differ a bit (mostly just the order is changed), and sometimes one or another is swapped (probably happens because of the color fixing code). Nothing that should break people's setup anyway (unless they actively depend on color order... which i think no one does lol).

Will try and see if i can include more improvements to release together with this on 0.4, but if it takes too long i will release it with this fix only.

**Comment by loiccoyle** [comment]
Perfect, thanks a lot!

**Comment by Misterio77** [comment]
Sorry for the delay, getting this new version release right now.

**Comment by loiccoyle** [comment]
No worries !

**Pull request merged**
