### PR TITLE
Improve readability of README

### PR DESCRIPTION
**Pull request by k4j8**
PR includes typos and grammar fixes in addition to changing the order of the README to prioritize configuration of flavours over Base16 examples.

### CODE REVIEW

**Comment by k4j8** [comment]
Awesome project! I'm really glad your tool exists. Some of the changes are subjective, so please modify or reject entirely to your preference. I did include the grammar fixes from the other PR. Thanks again for making such a fun tool.

**Comment by Misterio77** [comment]
Hey! Thanks a lot for the corrections :). I ended up merging #50 first, so I'll go ahead and resolve the conflicts here

**Comment by Misterio77** [comment]
Done! My changes were just removing the backticks around `hook` default value (as its not literally `none`), as well as the paragraph about my (old) `generate` usecase.

**Comment by Misterio77** [comment]
Merging this now, please feel free to create a follow up PR if you see anything else that could be improved.

Thanks again!

**Pull request merged**
